### ISSUE TITLE
sgx-test fails on executing sim-debug docker pipeline

### ISSUE THREAD

**Issue by Saxenauts** [mesalock-linux/mesatee#25]
Hello. 

I am trying to build and run mesaTEE inside docker. I want to develop and debug the capabilities on a non SGX machine (GCP VM). 

I execute the drone pipeline with this command: 

```
sudo drone exec --pipeline sim_release --trusted
```
And I receive an assertion error in the protected_fs.rs test as called by sgx-test
Lines 285-286 in protected_fs.rs

```
let opt = ProtectedFile::open_ex("/dev/isgx", &key);
            assert_eq!(opt.is_ok(), true); 
```

This code is looking for sgx installation in the machine, which I don't have. 
And in the sim_debug pipeline in .drone.yml , the volume to isgx ('/dev/isgx') is not attached. 

My question is, can I skip this assertion, or 
**Is there anyway I can test and develop on mesaTEE on a non SGX machine in some sort of a simulator like in Asylo ?** 

Thanks

**Comment by mssun** [comment]
Thanks for your report. **The workflow you are describing is totally fine for testing and developing  MesaTEE on a non-SGX machine.**

However, the `make sgx-test` command line in the `sim_release` pipeline runs unittest on the protected_fs module, which assume the testing machine has sgx device (this assumption may be not correct in `SGX_MODE=SW`). And it wired that our CI also didn't catch this issue. I need to further investigate the root cause.

To solve it, you can comment the following line in to disable the unit test of protected_fs as a workaround:

https://github.com/mesalock-linux/mesatee/blob/cd75585fbd2733b0784b315a22b88ce40c10a9bd/tests/module_test.sh#L6

Thanks again.

**Comment by Saxenauts** [comment]
Thank you. Closing the issue
